### PR TITLE
extconf.rb issues

### PR DESCRIPTION
**Pull request by rinkevichjm**
wx compiler can be clang while ruby uses gcc these can be the same compiler in OS X 
c++11 headers not handled right attempts to use tr1 headers
$LDFLAGS has libpaths that don't exist

Note clang doesn't have C++03 tr1 library and never will. Your current extconf.rb fails with all versions of clang as extconf doesn't support C++11. It always has. now wx should check definition of __cplusplus__ and correctly include the correct headers, but it does not and may never. See https://cplusplusmusings.wordpress.com/2013/06/03/whats-up-with-tr1-and-c11-and-libc/

### CODE REVIEW

**Comment by Hanmac** [comment]
first see that the test is failing so i will not merge it just now
then second C++11 are documented out for a reason because i dont need it in this extension, so no reason to enable and search for it (and osx is broken there too)

third to get the current state working, use macports to gain newer gcc and clang (which isnt broken than the current one on OSX is)
then better compile wxWidgets from source and also use rvm to install newer ruby than the current installed one (ruby version > 2.0 ) and there check that you use the same compiler.
That should work until i try to reimplementing your suggestions ( #extconf.rb# looks like cache/backup file so the mask "#.#" will added to the ignore mask)

i will add the gcc == clang version check,
then i will add that the -L and -l paths are cleaned from non existing stuff, (but i will use a bit of better coding)
but the check about type_traits and unordered_map looks that i doesnt seem to need that (wx does, but not i because i dont need C++11 as i said above)

**Comment by rinkevichjm** [comment]
This now passes sometimes and when it doesn't it is missing a path to gdk/gdk.h in the gtk install. Since I don't have gtk on Linux. I'm not certain why.

**Comment by Hanmac** [comment]
are you switched from OSX to linux?

and how do you use wx because only if wx is build against gtk is does include gtk stuff too (which you might need when you use a wx which was build against gtk)

to fix it, just install the right gtk+-x11 and gdk-x11 stuff to get it working.

**Comment by rinkevichjm** [comment]
I'm looking at that obtuse pkg-config stuff that is in there I think both flags strings need splitting to arrays and check the CFLAGS to see in the pkg flags is not included and add it if it is not include. Then rejoin the CFLAGS. 
PS I use wxmac not gtk

**Comment by rinkevichjm** [comment]
Passes now.

**Comment by Hanmac** [comment]
that should not work, i dont know how it can ever pass, because as you can see
it does need "wx-config" because "pkg_config" does not work / should not work
it might work on your system but i can tell you it might not work on other systems like windows

and you use pkg_config wrong,
`The values obtained are appended to +$CFLAGS+, +$LDFLAGS+ and +$libs+.`
so you dont need to do that yourself

i will try to rewrite it myself, but your coding style seems to be to bad to be merged

**Comment by rinkevichjm** [comment]
Use the code as is. It will work. Read the source for pkg_config at http://ruby-doc.org/stdlib-2.2.2/libdoc/mkmf/rdoc/MakeMakefile.html#method-i-pkg_config
Using pkg_config with pkg "wx" and option="desiredflags" causes it to take
elsif find_executable0(pkgconfig = "#{pkg}-config")
and define get as
  get ||= proc {|opt|
      opt = IO.popen("#{pkgconfig} --#{opt}", err[[:child, :out], &:read)
      opt.strip if $?.success?
    }
that causes a shell command of "wx-config --desiredflags" to be run and output captured
--------
now when pkg is "g%k*" the first elseif is taken and get is
    get = proc {|opt|
      opt = IO.popen("#{$PKGCONFIG} --#{opt} #{pkg}", err[[:child, :out], &:read)
      opt.strip if $?.success?
    }
so that pkg-config --opt g%k* is run and $CFLAGS and $libs are set and although this source shows $CXXFLAGS being set that doesn't happen.

**Comment by rinkevichjm** [comment]
This one can be merged. 
Damn Ruby pkg_config was broken in some versions.

**Pull request closed without merging**
